
version: 2.1

executors:
  go-114:
    docker:
      # https://hub.docker.com/layers/circleci/golang/1.14-node/images/sha256-2190fa9a5f81e3cb4397147d11aeaa88c22e6e35d401eead90195925230e071d?context=explore
      - image: circleci/golang:1.14-node
    working_directory: /go/src/github.com/kemokemo/imgdiff

jobs:
  test:
    executor: go-114
    steps:
      - checkout
      - run: go version
      - run: go get -v -t -d ./...
      - run: go test -v -cover -coverprofile=coverage.out ./...
  lint:
    executor: go-114
    steps:
      - checkout
      - run: go get -v -t -d ./...
      # see here: https://github.com/golang/lint/issues/415#issuecomment-511234597
      - run: go get -u golang.org/x/lint/golint
      - run: golint ./...
      - run: go vet ./...
  build:
    executor: go-114
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build
  deploy:
    executor: go-114
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go get -v -t -d ./...
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: mkdir release
      - run: gox -output "./release/{{.Dir}}_{{.OS}}_{{.Arch}}"  ./ ./...
      - run: ghr -u $CIRCLE_PROJECT_USERNAME $CIRCLE_TAG release/

workflows:
  version: 2
  test, lint and build:
    jobs:
      - test
      - lint
      - build:
          requires:
            - lint
  deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
